/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class FirstEntity : FirstEntityBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/FirstEntity.def
	// Please inherit and implement "class FirstEntity : FirstEntityBase"
	public abstract class FirstEntityBase : Entity
	{
		public EntityBaseEntityCall_FirstEntityBase baseEntityCall = null;
		public EntityCellEntityCall_FirstEntityBase cellEntityCall = null;

		public AVATAR_INFOS characters = new AVATAR_INFOS();
		public virtual void onCharactersChanged(AVATAR_INFOS oldValue) {}
		public List<Int32> test = new List<Int32>();
		public virtual void onTestChanged(List<Int32> oldValue) {}

		public abstract void onAddEquip(Int32 arg1); 
		public abstract void onEnter(); 
		public abstract void onRemoveEquip(Int32 arg1); 

		public FirstEntityBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_FirstEntityBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_FirstEntityBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["FirstEntity"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 4:
					Int32 onAddEquip_arg1 = stream.readInt32();
					onAddEquip(onAddEquip_arg1);
					break;
				case 1:
					onEnter();
					break;
				case 5:
					Int32 onRemoveEquip_arg1 = stream.readInt32();
					onRemoveEquip(onRemoveEquip_arg1);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["FirstEntity"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 1:
						AVATAR_INFOS oldval_characters = characters;
						characters = ((DATATYPE_AVATAR_INFOS)EntityDef.id2datatypes[22]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onCharactersChanged(oldval_characters);
						}
						else
						{
							if(inWorld)
								onCharactersChanged(oldval_characters);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 3:
						List<Int32> oldval_test = test;
						test = ((DATATYPE_AnonymousArray_23)EntityDef.id2datatypes[23]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onTestChanged(oldval_test);
						}
						else
						{
							if(inWorld)
								onTestChanged(oldval_test);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["FirstEntity"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			AVATAR_INFOS oldval_characters = characters;
			Property prop_characters = pdatas[4];
			if(prop_characters.isBase())
			{
				if(inited && !inWorld)
					onCharactersChanged(oldval_characters);
			}
			else
			{
				if(inWorld)
				{
					if(prop_characters.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCharactersChanged(oldval_characters);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			List<Int32> oldval_test = test;
			Property prop_test = pdatas[5];
			if(prop_test.isBase())
			{
				if(inited && !inWorld)
					onTestChanged(oldval_test);
			}
			else
			{
				if(inWorld)
				{
					if(prop_test.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onTestChanged(oldval_test);
					}
				}
			}

		}
	}
}